// <auto-generated />
using System;
using MealPlanner.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MealPlanner.Migrations
{
    [DbContext(typeof(MealPlannerDBContext))]
    [Migration("20260212060107_recipeSeedData")]
    partial class recipeSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MealPlanner.Models.Meal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("RepeatRule")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Meal");
                });

            modelBuilder.Entity("MealPlanner.Models.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Directions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ingredients")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Recipe");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Directions = "",
                            Ingredients = "",
                            Name = "Oatmeal Cookies"
                        },
                        new
                        {
                            Id = -2,
                            Directions = "",
                            Ingredients = "",
                            Name = "Spaghetti All'assassina"
                        },
                        new
                        {
                            Id = -3,
                            Directions = "",
                            Ingredients = "",
                            Name = "Spaghetti and Meatballs"
                        },
                        new
                        {
                            Id = -4,
                            Directions = "",
                            Ingredients = "",
                            Name = "Vegan Spaghetti with Mushrooms"
                        },
                        new
                        {
                            Id = -5,
                            Directions = "",
                            Ingredients = "",
                            Name = "Baked Spaghetti Casserole"
                        },
                        new
                        {
                            Id = -6,
                            Directions = "",
                            Ingredients = "",
                            Name = "Mac 'n Cheese Casserole"
                        },
                        new
                        {
                            Id = -7,
                            Directions = "",
                            Ingredients = "",
                            Name = "Homemade Mac 'n Cheese"
                        },
                        new
                        {
                            Id = -8,
                            Directions = "",
                            Ingredients = "",
                            Name = "Mushroom Steak Salad"
                        },
                        new
                        {
                            Id = -9,
                            Directions = "",
                            Ingredients = "",
                            Name = "Ceasar Salad"
                        });
                });

            modelBuilder.Entity("MealPlanner.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("MealPlanner.Models.UserDietaryRestriction", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<int>("UserId1")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex("UserId1");

                    b.ToTable("UserDietaryRestriction");
                });

            modelBuilder.Entity("MealPlanner.Models.UserNutritionPreference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("B12Target")
                        .HasColumnType("int");

                    b.Property<int?>("CalciumTarget")
                        .HasColumnType("int");

                    b.Property<int?>("CalorieTarget")
                        .HasColumnType("int");

                    b.Property<int?>("CarbTarget")
                        .HasColumnType("int");

                    b.Property<int?>("FatTarget")
                        .HasColumnType("int");

                    b.Property<int?>("FiberTarget")
                        .HasColumnType("int");

                    b.Property<int?>("FolateTarget")
                        .HasColumnType("int");

                    b.Property<int?>("IronTarget")
                        .HasColumnType("int");

                    b.Property<int?>("PotassiumTarget")
                        .HasColumnType("int");

                    b.Property<int?>("ProteinTarget")
                        .HasColumnType("int");

                    b.Property<int?>("VitaminATarget")
                        .HasColumnType("int");

                    b.Property<int?>("VitaminCTarget")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UserNutritionPreference");
                });

            modelBuilder.Entity("MealPlanner.Models.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActivityLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("HeightInInches")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("age")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserProfile");
                });

            modelBuilder.Entity("MealRecipe", b =>
                {
                    b.Property<int>("MealsId")
                        .HasColumnType("int");

                    b.Property<int>("RecipesId")
                        .HasColumnType("int");

                    b.HasKey("MealsId", "RecipesId");

                    b.HasIndex("RecipesId");

                    b.ToTable("MealRecipe");
                });

            modelBuilder.Entity("MealPlanner.Models.Meal", b =>
                {
                    b.HasOne("MealPlanner.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MealPlanner.Models.UserDietaryRestriction", b =>
                {
                    b.HasOne("MealPlanner.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MealRecipe", b =>
                {
                    b.HasOne("MealPlanner.Models.Meal", null)
                        .WithMany()
                        .HasForeignKey("MealsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MealPlanner.Models.Recipe", null)
                        .WithMany()
                        .HasForeignKey("RecipesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
