name: Build and run e2e acceptance tests against a live database

on:
  push:
    branches:
      - setup-staging

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mssql:
        image: mcr.microsoft.com/mssql/server:2025-latest
        env:
          MSSQL_SA_PASSWORD: Testp@ssw0rd
          ACCEPT_EULA: 'Y'
        ports:
          - 1433:1433

    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
          dotnet-quality: 'preview'
      - name: Restore dependencies
        run: dotnet restore ./src/MealPlanner/MealPlanner.Tests/MealPlanner.IntegrationTests.csproj
      - name: Build test project
        run: dotnet build --no-restore ./src/MealPlanner/MealPlanner.IntegrationTests/Mealplanner.IntegrationTests.csproj
      - name: Test
        run: dotnet test --no-build ./src/MealPlanner/MealPlanner.Tests/Mealplanner.Tests.csproj
        env:
          ConnectionString: "Server=localhost,1433;Initial Catalog=OneBiteTesting;User Id=sa;Password=Testp@ssw0rd;"
