name: Integration Test

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Setup dotnet
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.x'

      - name: Install dependencies
        working-directory: ./src/MealPlanner/MealPlanner.IntegrationTests
        run: dotnet restore
      - name: Build test project
        run: dotnet build --no-restore ./src/MealPlanner/MealPlanner.IntegrationTests/MealPlanner.IntegrationTests.csproj

      - name: Test
        run: dotnet test --no-build ./src/MealPlanner/MealPlanner.IntegrationTests/MealPlanner.IntegrationTests.csproj