name: Integration Test

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Setup dotnet
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.x'

      - name: Run integration tests
        working-directory: ./src/MealPlanner/MealPlanner.IntegrationTests
        run: dotnet test Mealplanner.IntegrationTests.csproj --verbosity normal