name: Integration Test
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
          dotnet-quality: 'preview'
      - name: Restore dependencies
        run: dotnet restore ./src/MealPlanner/MealPlanner.Tests/MealPlanner.Tests.csproj
      - name: Build test project
        run: dotnet build --no-restore ./src/MealPlanner/MealPlanner.Tests/MealPlanner.Tests.csproj
      - name: Test
        run: dotnet test --no-build ./src/MealPlanner/MealPlanner.Tests/MealPlanner.Tests.csproj